/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAcessosRouteImport } from './routes/_app.acessos'
import { Route as AppControleRouteImport } from './routes/_app.controle'
import { Route as AppFaturasRouteImport } from './routes/_app.faturas'
import { Route as AppFluxoCaixaRouteImport } from './routes/_app.fluxo-caixa'
import { Route as AppInventarioRouteImport } from './routes/_app.inventario'
import { Route as AppRelatorioRouteImport } from './routes/_app.relatorio'
import { Route as AppResultadoRouteImport } from './routes/_app.resultado'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcessosRoute = AppAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AppRoute,
} as any)
const AppControleRoute = AppControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturasRoute = AppFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioRoute = AppRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadoRoute = AppResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acessos': typeof AppAcessosRoute
  '/controle': typeof AppControleRoute
  '/faturas': typeof AppFaturasRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/inventario': typeof AppInventarioRoute
  '/relatorio': typeof AppRelatorioRoute
  '/resultado': typeof AppResultadoRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acessos': typeof AppAcessosRoute
  '/controle': typeof AppControleRoute
  '/faturas': typeof AppFaturasRoute
  '/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/inventario': typeof AppInventarioRoute
  '/relatorio': typeof AppRelatorioRoute
  '/resultado': typeof AppResultadoRoute
  '/': typeof AppIndexRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/acessos': typeof AppAcessosRoute
  '/_app/controle': typeof AppControleRoute
  '/_app/faturas': typeof AppFaturasRoute
  '/_app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/relatorio': typeof AppRelatorioRoute
  '/_app/resultado': typeof AppResultadoRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acessos'
    | '/controle'
    | '/faturas'
    | '/fluxo-caixa'
    | '/inventario'
    | '/relatorio'
    | '/resultado'
    | '/api/public/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/acessos'
    | '/controle'
    | '/faturas'
    | '/fluxo-caixa'
    | '/inventario'
    | '/relatorio'
    | '/resultado'
    | '/'
    | '/api/public/download'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/acessos'
    | '/_app/controle'
    | '/_app/faturas'
    | '/_app/fluxo-caixa'
    | '/_app/inventario'
    | '/_app/relatorio'
    | '/_app/resultado'
    | '/_app/'
    | '/api/public/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acessos': {
      id: '/_app/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AppAcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/controle': {
      id: '/_app/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof AppControleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faturas': {
      id: '/_app/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AppFaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-caixa': {
      id: '/_app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio': {
      id: '/_app/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AppRelatorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resultado': {
      id: '/_app/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof AppResultadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcessosRoute: typeof AppAcessosRoute
  AppControleRoute: typeof AppControleRoute
  AppFaturasRoute: typeof AppFaturasRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppRelatorioRoute: typeof AppRelatorioRoute
  AppResultadoRoute: typeof AppResultadoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcessosRoute: AppAcessosRoute,
  AppControleRoute: AppControleRoute,
  AppFaturasRoute: AppFaturasRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppRelatorioRoute: AppRelatorioRoute,
  AppResultadoRoute: AppResultadoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
