/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as IndexRouteImport } from './routes/index'

const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faturas': typeof FaturasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faturas': typeof FaturasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faturas': typeof FaturasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faturas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faturas'
  id: '__root__' | '/' | '/faturas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaturasRoute: typeof FaturasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaturasRoute: FaturasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
